# Generated by Django 3.0.3 on 2020-04-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelexample', '0004_auto_20200421_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='shirt_size',
            field=models.IntegerField(choices=[(90, 'Small'), (100, 'Medium'), (105, 'Large'), (110, 'Free')], default=110),
        ),
    ]
