# Generated by Django 3.0.3 on 2020-04-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelexample', '0006_auto_20200422_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(help_text='이름', max_length=30, verbose_name='test입력'),
        ),
    ]
