# Generated by Django 3.0.3 on 2020-04-22 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelexample', '0008_pizza_topping'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakePizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelexample.Pizza')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelexample.Topping')),
            ],
        ),
    ]
