# Generated by Django 3.0.3 on 2020-04-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelexample', '0009_makepizza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
    ]
